version: '3.7'
services:
    adminer:
        image: 'adminer:latest'
        ports:
            - '8081:8080'
        depends_on: 
            - mysql
    mysql:
        image: 'mysql:5.7'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=vse_khorosho
            - MYSQL_ROOT_PASSWORD=root
    php:
        build: ./docker/php
        volumes:
            - './:/var/www/html'
        environment:
            - 'PHP_EXTENSIONS=pdo_mysql,intl,opcache,apcu,xdebug'
        depends_on: 
            - mysql
       
    nginx:
        image: 'nginx'
        ports:
            - '8080:80'
        volumes:
            - './:/var/www/html'
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
